# -*- coding: utf-8 -*-
"""Výlet rozlučka streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etct5uTVkjghk-SYUARPeNbG81PRGoUe
"""

import streamlit as st
import random

# Tvoje texty doslova, bez jediné změny znaku
trasa = [
    "Růžodol - park Opičák. Je to kombinace vašich příjmení, když máš trochu fantazie. Není to cute?",
    "Zbytky budování Hitlerovy dálnice - to jsem tak trochu vybrala kvůli dnešnímu datu.",
    "Srní sedlo. Hihi, to je vtipný, když jsi Rudolfová, to je srna taková tvoje příbuzná.",
    "Kaliště - to je místo, kde se prasata čvachtají v bahně. Přišlo mi to ale taky vtipný, protože pěkně zakalíme.",
    "Černá hora. K tomu nemám žádný vtip, promiň. Jen mi to přišlo na mapách hezký.",
    "Ještěď - náš cíl. Až tam dojdeme, tak bych si tam počkala na západ slunce. Mohlo by to být mega pěkný!"
]

ukoly = [
    "Udělej reklamu nějaké věci, kterou tady vidíš, ve španělštině.",
    "Pantomimou předveď tvůj oblíbený film.",
    "Vybalancuj pět kamenů na sebe do věže jednou rukou.",
    "Zavolej Jirkovi a řekni mu něco hezkýho.",
    "Za 30 sekund vyjmenuj 15 druhů ovoce."
]

ukol2 = "Vyřeš osmisměrku https://puzzel.org/en/wordseeker/play?p=-OxlQqal9KRt-xTOQjol"
ukol6 = "Vyřeš posouvačku https://puzzel.org/en/slidingpuzzle/play?p=-OxjcWxOmDeLa_zNkdSA"

otazky = [
    "Jaký film/seriál má tak rád, že by ho dokázal odříkat celý nazpaměť?",
    "Co je Jirkův nejmíň užitečný talent?",
    "Jaká věc, kterou někdo dělá, ho rozčiluje mnohem víc, než by měla?",
    "Kdyby vypukla zombie apokalypsa, jakou nepraktickou věc by si chtěl vzít z domova?",
    "Co bylo Jirkovo vysněné povolání, když byl malý?",
    "Co je Jirkovo „comfort food“?",
    "Jaký starý kus oblečení pořád nosí a odmítá ho vyhodit?",
    "Jaké jídlo/ingredienci odmítá jíst?",
    "Za co nejbizarnějšího Jirka kdy utratil peníze?",
    "Jaký dárek, který jsi mu dala, mu udělal největší radost?"
]

# Technické nastavení webové stránky
if 'kolo' not in st.session_state:
    st.session_state.kolo = 1
    st.session_state.otazky_pool = otazky.copy()
    st.session_state.ukoly_pool = ukoly.copy()
    st.session_state.text_kola = ""

# ÚVOD
st.write("Ahoj, jmenuju se Róza a ráda chodím na výlety.\nSlyšela jsem, že jste s kámoškama na víkend v horách, tak jsem si pro vás jeden připravila.\nNebudu ti ale říkat, kam jdeme. To je překvápko a musíš na to postupně přijít sama.")

jak_se_mas = st.text_input("Teď ale první otázka. Jak se máš?\n")

if jak_se_mas:
    st.write("Super. Tak můžeme začít!\nNa každém místě na naší trase si budeš moct vybrat, jestli chceš odpovědět na otázku, která prověří, jak dobře Jirku znáš, nebo splnit nějaký úkol.\nPo správné odpovědi nebo úspěšném splnění úkolu ti prozradím další bod naší trasy.\nJestli ale odpovíš špatně, nebo se ti úkol nepovede splnit, mustíš si dát panáka, abych ti prozradila, kam máš jít dál.\nJakýkoliv další otázky směruj na Aničku, jsme domluvené. Ona tě zároveň bude i hlídat, jestli jsi odpověděla správně.")
    
    muzeme_vyrazit = st.text_input("Můžeme vyrazit?\n")
    
    if muzeme_vyrazit:
        # HRACÍ KOLA 1-6
        if 1 <= st.session_state.kolo <= 6:
            kolo = st.session_state.kolo
            st.write(f"### Kolo {kolo} z 6")
            
            odpoved = st.text_input("Chceš radši otázku, nebo úkol?\n", key=f"vstup_{kolo}")
            
            if odpoved:
                if odpoved.lower() in ["úkol", "ukol"] and not st.session_state.text_kola:
                    if kolo == 2:
                        st.session_state.text_kola = ukol2
                    elif kolo == 6:
                        st.session_state.text_kola = ukol6
                    else:
                        vybrany_ukol = random.choice(st.session_state.ukoly_pool)
                        st.session_state.ukoly_pool.remove(vybrany_ukol)
                        st.session_state.text_kola = f" {vybrany_ukol}"
                        
                elif odpoved.lower() in ["otázku", "otazku", "otázka", "otazka"] and not st.session_state.text_kola:
                    vybrana_otazka = random.choice(st.session_state.otazky_pool)
                    st.session_state.otazky_pool.remove(vybrana_otazka)
                    st.session_state.text_kola = f" {vybrana_otazka}"
                    
                if st.session_state.text_kola:
                    st.write(st.session_state.text_kola)
                    
                    # Tlačítko se změnilo na textové pole. Až do něj napíše odpověď, odemkne se cíl.
                    muzeme_dal = st.text_input("Můžeme jít dál?\n", key=f"odpoved_na_ukol_nebo_otazku_{kolo}")
                    
                    if muzeme_dal:
                        dalsi_misto = trasa[kolo - 1]
                        
                        if kolo == 2:
                            st.write(f" Super, to jsem ráda! Náš další cíl jsou {dalsi_misto}\n")
                        else:
                            st.write(f" Super, to jsem ráda! Náš další cíl je {dalsi_misto}\n")
                        
                        if st.button("Až tam dojdeš, ozvi se mi :)\n", key=f"button_ozvi_{kolo}"):
                            st.session_state.kolo += 1
                            st.session_state.text_kola = ""
                            st.rerun()

        # KONEC HRY
        else:
            st.write("Tak jsme tady! Doufám, že se ti náš výlet líbil tak jako mně. Užijte si ještě zbytek rozlučky a zase tě někdy ráda uvidím :)")
