# -*- coding: utf-8 -*-
"""Výlet rozlučka streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etct5uTVkjghk-SYUARPeNbG81PRGoUe
"""

import streamlit as st
import random

# Tvoje texty doslova, bez jediné změny znaku
trasa = [
    "Růžodol - park Opičák. Je to kombinace vašich příjmení, když máš trochu fantazie. Není to cute?",
    "Zbytky budování Hitlerovy dálnice - to jsem tak trochu vybrala kvůli dnešnímu datu.",
    "Karlov pod Ještědem - vlaková zastávka",
    "Srní sedlo. Hihi, to je vtipný, když jsi Rudolfová, to je srna taková tvoje příbuzná.",
    "Rozsocha",
    "Kaliště - to je místo, kde se prasata čvachtají v bahně. Přišlo mi to ale taky vtipný, protože pěkně zakalíme.",
    "Černá hora",
    "Výpřež",
    "Ještěď - náš cíl. Až tam dojdeme, tak bych si tam počkala na západ slunce. Mohlo by to být mega pěkný!"
]

ukoly = [
    "Po svatbě tě čeká další životní změna. Udělej reklamu nějaké věci, kterou tady vidíš, ve španělštině, aby sis natrénovala roli obchoďačky.",
    "Jako nevěsta musíš být připravena na každou situaci – co kdybys nestíhala k oltáři, nebo ti někdo chtěl sníst tvůj kousek dortu? Obleč se jako nevěsta (i s podpatky) a uběhni vytyčenou trasu.",
    "Abys zvládla ve svatební den tu nejdůležitější věc s jistotou, natrénuj si to teď ve ztížených podmínkách. Poslepu nasaď prsten jedné z tvých kamarádek.",
    "Tvého budoucího manžela bys měla znát z každého úhlu. Poznej, která fotka ukazuje Jirkovu část těla (když uhodneš 4, nemusíš panákovat).",
    "Když budeš na Jirku někdy naštvaná, musíš si uvědomit, že i on je pořád „just a boy“. Poznej, na které fotce je Jirka jako miminko, a kde je na fotce ze školky a základky.",
    "Svatba je už za dva týdny, a tak je na čase, aby sis připravila svatební slib. Holky ti určitě rády pomůžou s výběrem správných slov, které ve slibu rozhodně nesmí chybět.",
    "Komunikace je základ zdravého vztahu. Zavolej Jirkovi a řekni mu něco hezkýho."

]

ukol2 = "Osmička v numerologii symbolizuje moc. Co teprve, když osmičky jsou v datu dvě? Vyřeš osmisměrku tématickou k dnešnímu dni: https://puzzel.org/en/wordseeker/play?p=-OxlQqal9KRt-xTOQjol"
ukol8 = "Spolu do sebe zapadáte jako dílky skládačky <3 https://puzzel.org/en/slidingpuzzle/play?p=-OxjcWxOmDeLa_zNkdSA"

otazky = [
    "Jaký film/seriál má tak rád, že by ho dokázal odříkat celý nazpaměť?",
    "Co je Jirkův nejmíň užitečný talent?",
    "Jaká věc, kterou někdo dělá, ho rozčiluje mnohem víc, než by měla?",
    "Kdyby vypukla zombie apokalypsa, jakou nepraktickou věc by si chtěl vzít z domova?",
    "Co bylo Jirkovo vysněné povolání, když byl malý?",
    "Co je Jirkovo „comfort food“?",
    "Jaký starý kus oblečení pořád nosí a odmítá ho vyhodit?",
    "Jaké jídlo/ingredienci odmítá jíst?",
    "Za co nejbizarnějšího Jirka kdy utratil peníze?",
    "Jaký dárek, který jsi mu dala, mu udělal největší radost?"
]

# Technické nastavení webové stránky
if 'kolo' not in st.session_state:
    st.session_state.kolo = 1
    st.session_state.otazky_pool = otazky.copy()
    st.session_state.ukoly_pool = ukoly.copy()
    st.session_state.text_kola = ""

# ÚVOD
st.write("Ahoj, jmenuju se Róza a ráda chodím na výlety.\nSlyšela jsem, že jste s kámoškama na víkend v horách, tak jsem si pro vás jeden připravila.\nNebudu ti ale říkat, kam jdeme. To je překvápko a musíš na to postupně přijít sama.")

jak_se_mas = st.text_input("Teď ale první otázka. Jak se máš?\n")

if jak_se_mas:
    st.write("Super. Tak můžeme začít!\nNa každém místě na naší trase si budeš moct vybrat, jestli chceš odpovědět na otázku, která prověří, jak dobře Jirku znáš, nebo splnit nějaký úkol.\nPo správné odpovědi nebo úspěšném splnění úkolu ti prozradím další bod naší trasy.\nJestli ale odpovíš špatně, nebo se ti úkol nepovede splnit, mustíš si dát panáka, abych ti prozradila, kam máš jít dál.\nJakýkoliv další otázky směruj na Aničku, jsme domluvené. Ona tě zároveň bude i hlídat, jestli jsi odpověděla správně.")
    
    muzeme_vyrazit = st.text_input("Můžeme vyrazit?\n")
    
    if muzeme_vyrazit:
        # HRACÍ KOLA 1-6
        if 1 <= st.session_state.kolo <= 8:
            kolo = st.session_state.kolo
            
            odpoved = st.text_input("Chceš radši otázku, nebo úkol?\n", key=f"vstup_{kolo}")
            
            if odpoved:
                if odpoved.lower() in ["úkol", "ukol"] and not st.session_state.text_kola:
                    if kolo == 2:
                        st.session_state.text_kola = ukol2
                    elif kolo == 8:
                        st.session_state.text_kola = ukol8
                    else:
                        vybrany_ukol = random.choice(st.session_state.ukoly_pool)
                        st.session_state.ukoly_pool.remove(vybrany_ukol)
                        st.session_state.text_kola = f" {vybrany_ukol}"
                        
                elif odpoved.lower() in ["otázku", "otazku", "otázka", "otazka"] and not st.session_state.text_kola:
                    vybrana_otazka = random.choice(st.session_state.otazky_pool)
                    st.session_state.otazky_pool.remove(vybrana_otazka)
                    st.session_state.text_kola = f" {vybrana_otazka}"
                    
                if st.session_state.text_kola:
                    st.write(st.session_state.text_kola)
                    
                    muzeme_dal = st.text_input("Můžeme jít dál?\n", key=f"odpoved_na_ukol_nebo_otazku_{kolo}")
                    
                    if muzeme_dal:
                        dalsi_misto = trasa[kolo - 1]
                        
                        if kolo == 2:
                            st.write(f" Super, to jsem ráda! Náš další cíl jsou {dalsi_misto}\n")
                        else:
                            st.write(f" Super, to jsem ráda! Náš další cíl je {dalsi_misto}\n")
                        
                        # Tlačítko nahrazeno textovým polem pro čistou konverzaci
                        dosla_jsem = st.text_input("Až tam dojdeš, ozvi se mi :)\n", key=f"dosla_jsem_{kolo}")
                        
                        if dosla_jsem:
                            st.session_state.kolo += 1
                            st.session_state.text_kola = ""
                            st.rerun()

        # KONEC HRY
        else:
            st.write("Tak jsme tady! Doufám, že se ti náš výlet líbil tak jako mně. Užijte si ještě zbytek rozlučky a zase tě někdy ráda uvidím :)")
